# Generated by Django 5.0.4 on 2024-07-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_image', models.ImageField(upload_to='image/')),
                ('home_image', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('established', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('production_hour', models.IntegerField(max_length=200)),
                ('production_day', models.IntegerField(max_length=200)),
                ('production_year', models.IntegerField(max_length=200)),
            ],
        ),
    ]
