# Generated by Django 5.0.4 on 2024-07-03 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('date', models.DateField(auto_now_add=True)),
                ('headline', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='statistic',
            name='production_day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='production_hour',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='production_year',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='NewsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('bullet_points', models.TextField(help_text='Use commas to separate bullet points')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='APP.news')),
            ],
        ),
    ]
