# Generated by Django 5.0.4 on 2024-07-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_news_alter_statistic_production_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdetail',
            name='bullet_points',
            field=models.TextField(blank=True, help_text='Use commas to separate bullet points', null=True),
        ),
    ]
