# Generated by Django 5.0.4 on 2024-07-03 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_alter_newsdetail_bullet_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsdetail',
            name='bullet_points',
        ),
    ]
