# Generated by Django 4.2.13 on 2024-07-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_remove_newsdetail_bullet_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raw_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
