# Generated by Django 4.2.13 on 2024-07-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_raw_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('phone', models.IntegerField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='image/')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
