# Generated by Django 4.2.13 on 2024-07-04 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('hiring_process', models.TextField()),
                ('descriptions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='team_member',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=200)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement', to='APP.announcement')),
            ],
        ),
    ]
