# Generated by Django 4.2.13 on 2024-07-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0011_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='tree_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
