# Generated by Django 4.2.13 on 2024-07-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0012_statistic_tree_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='production_day',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='production_hour',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='production_year',
            field=models.CharField(max_length=200),
        ),
    ]
