# Generated by Django 4.2.13 on 2024-07-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0013_alter_statistic_production_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('upload', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
