# Generated by Django 4.2.13 on 2024-07-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0014_tenders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
