# Generated by Django 4.2.13 on 2024-07-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0016_annual_audited_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='tree_image',
        ),
        migrations.AddField(
            model_name='statistic',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
