# Generated by Django 4.2.13 on 2024-07-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0017_remove_statistic_tree_image_statistic_certificates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uploads', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='certificates',
        ),
    ]
