# Generated by Django 4.2.13 on 2024-07-15 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0018_certificates_about_remove_statistic_certificates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsdetail',
            name='news',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='NewsDetail',
        ),
    ]
