# Generated by Django 4.2.13 on 2024-07-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0019_remove_newsdetail_news_delete_news_delete_newsdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates_about',
            name='uploads',
        ),
        migrations.AddField(
            model_name='certificates_about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
